name = "mintable-token"
version = "1.4"
description = "Token that allows the owner to mint as many tokens as desired"
preset = "main"

[setting.salt]
defaultValue = "mintable-token"

[setting.name]
defaultValue = "Token"

[setting.symbol]
defaultValue = "TKN"

[setting.initialSupply]
defaultValue = "0"

[setting.owner]
defaultValue = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"

[contract.MintableToken]
artifact = "MintableToken"
from = "<%= settings.owner %>"
salt = "<%= settings.salt %>"
args = [
    "<%= settings.name %>",
    "<%= settings.symbol %>",
    "<%= settings.initialSupply %>",
]
highlight = true
