name = "mintable-token"
version = "1.4"
description = "Token that allows anyone to mint as many tokens as desired"
preset = "permissionless-mint"

[setting.salt]
defaultValue = "mintable-token"

[setting.name]
defaultValue = "Token"

[setting.symbol]
defaultValue = "TKN"

[setting.initialSupply]
defaultValue = "0"

[contract.MintableToken]
artifact = "MintableTokenPermissionlessMint"
salt = "<%= settings.salt %>"
args = [
    "<%= settings.name %>",
    "<%= settings.symbol %>",
    "<%= settings.initialSupply %>",
]
