name = "mintable-token"
version = "1.8"
description = "Token that allows the owner to mint as many tokens as desired"
preset = "main"

[setting.owner]

[setting.salt]
defaultValue = ""

[setting.name]
defaultValue = "Token"

[setting.symbol]
defaultValue = "TKN"

[setting.decimals]
defaultValue = "18"

[setting.initialSupply]
defaultValue = "0"

[contract.MintableToken]
artifact = "MintableToken"
salt = "<%= settings.salt %>"
args = [
		"<%= settings.owner %>",
    "<%= settings.name %>",
    "<%= settings.symbol %>",
		"<%= settings.decimals %>",
    "<%= settings.initialSupply %>",
]
create2 = true
highlight = true
