name = "mintable-token"
version = "3.0"
description = "Token that allows anyone to mint as many tokens as desired"
preset = "permissionless-mint"

[setting.salt]
defaultValue = ""

[setting.name]
defaultValue = "Token"

[setting.symbol]
defaultValue = "TKN"

[setting.decimals]
defaultValue = "18"

[contract.Token]
artifact = "MintableTokenPermissionlessMint"
salt = "<%= settings.salt %>"
args = [
    "<%= settings.name %>",
    "<%= settings.symbol %>",
		"<%= settings.decimals %>",
]
create2 = true
highlight = true
