name = "mintable-token"
version = "1.3"
description = "Token that allows anyone to mint as many tokens as desired"

[setting.name]
defaultValue = "Token"

[setting.symbol]
defaultValue = "TKN"

[setting.initialSupply]
defaultValue = "0"

[contract.MintableToken]
artifact = "MintableTokenPermissionlessMint"
args = [
    "<%= settings.name %>",
    "<%= settings.symbol %>",
    "<%= settings.initialSupply %>",
]