name = "uma-oov3"
version = "<%= package.version %>"
preset = "main"
description = "Cannon package for the UMA Optimistic Oracle v3 contract"

[var.owner]
owner = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[var.fixed]
fixed = "0"

[var.weekly]
weekly = "0"

[var.defaultCurrency]
defaultCurrency = ""

[var.defaultLiveness]
defaultLiveness = "7200"

[pull.usdc]
source = "usdc:latest@main"

[pull.MockOracleAncillary]
source = "uma-mock-oracle-ancillary:latest@main"

[deploy.IdentifierWhitelist]
artifact = "IdentifierWhitelist"

[deploy.AddressWhitelist]
artifact = "AddressWhitelist"

[deploy.Store]
artifact = "Store"
args = [
  "<%= settings.fixed %>",
  "<%= settings.weekly %>",
  "0x0000000000000000000000000000000000000000"
]

[deploy.Finder]
artifact = "Finder"
from = "<%= settings.owner %>"

[invoke.add_oracle_impl]
target = ["Finder"]
func = "changeImplementationAddress"
from = "<%= settings.owner %>"
args = [
  "0x4f7261636c650000000000000000000000000000000000000000000000000000",
  "<%= MockOracleAncillary.MockOracleAncillary.address %>"
]

[invoke.add_iwhitelist_impl]
target = ["Finder"]
func = "changeImplementationAddress"
from = "<%= settings.owner %>"
args = [
  "0x4964656e74696669657257686974656c69737400000000000000000000000000",
  "<%= IdentifierWhitelist.address %>"
]

[invoke.add_awhitelist_impl]
target = ["Finder"]
func = "changeImplementationAddress"
from = "<%= settings.owner %>"
args = [
  "0x436f6c6c61746572616c57686974656c69737400000000000000000000000000",
  "<%= AddressWhitelist.address %>"
]

[invoke.add_store_impl]
target = ["Finder"]
func = "changeImplementationAddress"
from = "<%= settings.owner %>"
args = [
  "0x53746f7265000000000000000000000000000000000000000000000000000000",
  "<%= Store.address %>"
]

[deploy.OptimisticOracleV3]
artifact = "OptimisticOracleV3"
args = [
  "<%= contracts.Finder.address %>",
  "<%= usdc.FiatTokenProxy.address %>",
  "<%= settings.defaultLiveness %>"
]
highlight = true

depends = [
  "pull.usdc",
  "invoke.add_oracle_impl", 
  "invoke.add_iwhitelist_impl", 
  "invoke.add_awhitelist_impl", 
  "invoke.add_store_impl"
  ]
