name = "uma-mock-oracle-ancillary"
version = "1.0.1"
preset = 'main'
description = "Cannon package for the UMA Oracle contract"

[deploy.Timer]
artifact = "TimerOverride"

[deploy.Finder]
artifact = "FinderOverride"

[deploy.MockOracleAncillary]
artifact = "MockOracleAncillaryOverride"
args = [
  "<%= contracts.Finder.address %>",
  "<%= contracts.Timer.address %>",
]
