name = "universal-upgradeable-proxy"
version = "<%= package.version %>"
preset = 'oz'
description = "Universal Proxy using OpenZeppelin UUPS contracts"

[deploy.UUPSUpgradeableMock]
artifact = "UUPSUpgradeableMock"
create2 = true

# Override this setting in your own cannonfile to replace the implementation address with your own implementation contract address
[var.implementation]
implementation = "<%= contracts.UUPSUpgradeableMock.address %>"

[var.owner]
owner = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[var.abi]
abi = "<%= JSON.stringify(contracts.UUPSUpgradeableMock.abi) %>"

[var.initialCallData]
initialCallData = "0x"

[deploy.InitialProxy]
artifact = "ERC1967Proxy"
args = [
  "<%= contracts.UUPSUpgradeableMock.address %>",
  "<%= settings.initialCallData %>"
]
create2 = true

[invoke.upgrade_proxy_implementation]
target = ["InitialProxy"]
from = "<%= settings.owner %>"
abi = "UUPSUpgradeableMock"
func = "upgradeTo"
args = ["<%= settings.implementation %>"]
factory.Proxy.abi = "<%= settings.abi %>"
factory.Proxy.event = "Upgraded"
factory.Proxy.arg = 0
factory.Proxy.highlight = true
